[package]
name = "kris_kringle"
version = "0.1.0"
authors = ["maccod <maccora17@gmail.com>"]

[dependencies]
clap = "2.22"
rand = "0.3.*"
lettre = "0.6.2"
toml = "0.3"
serde = "0.9"
serde_derive = "0.9"